apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: mgmt-spoke1
  namespace: mgmt-spoke1
spec:
  baseDomain: example.com
  clusterName: mgmt-spoke1
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: mgmt-spoke1
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "mgmt-spoke1"
  pullSecretRef:
    name: assisted-deployment-pull-secret
